---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consolida-me-payments-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consolida-me-payments-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
