apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- hpa.yml
- service.yml

images:
- name: consolida-me-payments-api
  newName: brucorreia/consolida-me-payments-api
  newTag: c270fa359c18615d70a66bb3e1d7dadc6865174b
