---
apiVersion: v1
kind: Service
metadata:
  name: aplicamos-crawl
  labels:
    app: aplicamos-crawl
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: aplicamos-crawl

