---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: aplicamos-auth
  name: aplicamos-auth
spec:
  selector:
    matchLabels:
      app: aplicamos-auth
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: aplicamos-auth
    spec:
      containers:
        - name: aplicamos-auth
          image: brucorreia/aplicamos-auth:f74dcdcad991789a851c6580caf8a547e3ee207d
          envFrom:
          - secretRef:
              name: aplicamos-auth
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            requests:
              memory: "64M"
              cpu: "64m"
            limits:
              memory: "128M"
              cpu: "128m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
      imagePullSecrets:
      - name: regcred
