---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: aplicamos-auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aplicamos-auth
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
