apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- hpa.yml
- service.yml

images:
- name: aplicamos-auth
  newName: brucorreia/aplicamos-auth
  newTag: 16e23c09ce540f367712272810c546d180e28fe2
