apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- hpa.yml
- service.yml

images:
- name: aplicamos-auth
  newName: brucorreia/aplicamos-auth
  newTag: e155f5da6f99258356af5fb3c2d631bda2245923
