apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aplicamos-auth

resources:
- deployment.yml

images:
- name: aplicamos-auth
  newName: brucorreia/aplicamos-auth
  newTag: f74dcdcad991789a851c6580caf8a547e3ee207d
