---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: aplicamos-resumeregister
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aplicamos-resumeregister
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
