apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aplicamos-resumeregister

resources:
- deployment.yml
- hpa.yml
- service.yml

images:
- name: aplicamos-resumeregister
  newName: brucorreia/aplicamos-resumeregister
  newTag: cddcfbc5a9ceab846aec6fa59106ee95a55bb442
