---
apiVersion: batch/v1 
kind: CronJob
metadata:
  name: consolidame
spec:
  schedule: "0 06 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: consolidame
            image: brucorreia/consolida.me:4be924d597ea8c98acdf561c445042d437e3cbf1
            envFrom:
            - secretRef:
                name: consolida.me
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred
