---
apiVersion: batch/v1 
kind: CronJob
metadata:
  name: consolida.me
spec:
  schedule: "0 06 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: consolida.me
            image: brucorreia/consolida.me:b81c81c6125efa62ec0f766c30afd1ba72e1b74a
            envFrom:
            - secretRef:
                name: consolida.me
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred
