apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml

images:
- name: consolida.me
  newName: brucorreia/consolida.me
  newTag: c2398d101a9c886ee4394753193a9f915785014d
