apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml

images:
- name: consolida.me
  newName: brucorreia/consolida.me
  newTag: aab87d987af9d986199e547056be7bc66ab8bdf8
