---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: aplicamos-resumeregister-consumer
  name: aplicamos-resumeregister-consumer
spec:
  selector:
    matchLabels:
      app: aplicamos-resumeregister-consumer
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: aplicamos-resumeregister-consumer
    spec:
      containers:
        - name: aplicamos-resumeregister-consumer
          image: brucorreia/aplicamos-resumeregister-consumer:5c6b7891a725764edeba63924f20b8c26c01bde8
          envFrom:
          - secretRef:
              name: aplicamos-resumeregister-consumer
          resources:
            requests:
              memory: "32M"
              cpu: "32m"
            limits:
              memory: "64M"
              cpu: "64m"
      imagePullSecrets:
      - name: regcred
