apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aplicamos-resumeregister-consumer

resources:
- deployment.yml
- hpa.yml

images:
- name: aplicamos-resumeregister-consumer
  newName: brucorreia/aplicamos-resumeregister-consumer
  newTag: 5c6b7891a725764edeba63924f20b8c26c01bde8
