apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- hpa.yml

images:
- name: aplicamos-resumeregister-consumer
  newName: brucorreia/aplicamos-resumeregister-consumer
  newTag: d635759a880a6b5aa7f21288245b0ce9d8c41826
