---
apiVersion: v1
kind: Service
metadata:
  name: aplicamos-resumeregister-confirm
  labels:
    app: aplicamos-resumeregister-confirm
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: aplicamos-resumeregister-confirm

