apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- hpa.yml
- service.yml

images:
- name: aplicamos-recentprofiles
  newName: brucorreia/aplicamos-recentprofiles
  newTag: 376a505ae5c2490bd42a46eb37af7851b08d6a58
