---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consolida-me-api
spec:
  selector:
    matchLabels:
      app: consolida-me-api
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: consolida-me-api
    spec:
      containers:
        - name: consolida-me-api
          image: consolida-me-api
          envFrom:
          - secretRef:
              name: consolida-me-api
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            requests:
              memory: "64M"
              cpu: "64m"
            limits:
              memory: "128M"
              cpu: "128m"
      imagePullSecrets:
      - name: regcred
