apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- hpa.yml
- service.yml

images:
- name: consolida-me-api
  newName: brucorreia/consolida-me-api
  newTag: 875d29d724815cfd6fe9e5f88dc935e87942a78b
