apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- hpa.yml
- service.yml

images:
- name: consolida-me-api
  newName: brucorreia/consolida-me-api
  newTag: c20a7278cff1f50bc5b6be9f97d479f4e2f46a3a
