---
apiVersion: v1
kind: Service
metadata:
  name: consolida-me-api
  labels:
    app: consolida-me-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: consolida-me-api

